In [2]:
import numpy as np

In [14]:
# poles=np.array([0,1,-6,-6])
# zeros=np.array([-2])


poles=np.array([-13,0,0,10j,-10j])
#poles=np.array([0,0,-10,-3+2.5j,-3-2.5j])
zeros=np.array([-1,-9j,9j])


# poles=np.array([0,-1-3j,-1+3j])
# zeros=np.array([-1+np.sqrt(7)*1j,-1-np.sqrt(7)*1j])

poles**2*(poles+13)*(poles**2+100)

array([ 0.+0.j,  0.+0.j,  0.+0.j,  0.-0.j, -0.+0.j])

In [15]:
(zeros+1)*(zeros**2+81)

array([0.+0.j, 0.+0.j, 0.+0.j])

In [16]:
print(f"alpha={(np.sum(poles)-np.sum(zeros))/(len(poles)-len(zeros))}")

alpha=(-6+0j)


In [17]:
for l in range(1,len(poles)-len(zeros)+1):
    print(f"phi_{l}={(180+(l-1)*360)/(len(poles)-len(zeros))}")

phi_1=90.0
phi_2=270.0


In [18]:
for p1 in np.unique(poles):
    sum_p=0
    sum_z=0
    for p2 in poles:
        if p1!=p2:
            #print(np.degrees(np.arctan2(np.imag(p1-p2),np.real(p1-p2))))
            sum_p+=np.arctan2(np.imag(p1-p2),np.real(p1-p2))
    for z in zeros:
        sum_z+=np.arctan2(-np.imag(z-p1),-np.real(z-p1))
    
    q=np.sum(poles==p1)
    for l in range(np.sum(poles==p1)):
        print(f"for pole {p1}, departure angle {l+1}:",(1/q*(-180+np.degrees(sum_z)-np.degrees(sum_p)-(l)*360))%360,
              "degrees")

for pole (-13+0j), departure angle 1: 0.0 degrees
for pole (-0-10j), departure angle 1: 223.27918516632718 degrees
for pole 0j, departure angle 1: 270.0 degrees
for pole 0j, departure angle 2: 90.0 degrees
for pole 10j, departure angle 1: 136.72081483367282 degrees


In [19]:
for z1 in np.unique(zeros):
    sum_p=0
    sum_z=0
    for p2 in poles:
        #print(np.degrees(np.arctan2(np.imag(p1-p2),np.real(p1-p2))))
        sum_p+=np.arctan2(np.imag(z1-p2),np.real(z1-p2))
    for z in zeros:
        if z!=z1:
            sum_z+=np.arctan2(np.imag(z1-z),np.real(z1-z))
    q=np.sum(zeros==z1)
    for l in range(np.sum(zeros==z1)):
        print(f"for zero {z1}, arrival angle:",(1/q*(180-np.degrees(sum_z)+np.degrees(sum_p)+360*l))%360,"degrees")

for zero (-1+0j), arrival angle: 180.0 degrees
for zero (-0-9j), arrival angle: 138.9646547228561 degrees
for zero 9j, arrival angle: 221.0353452771439 degrees


In [119]:
zeros**2+2*zeros+8

array([11, 11])

In [19]:
for p1 in poles:
    sum_p=0
    sum_z=0
    for p2 in poles:
        if p1!=p2:
            #print(np.degrees(np.arctan2(np.imag(p1-p2),np.real(p1-p2))))
            sum_p+=np.arctan2(np.imag(p1-p2),np.real(p1-p2))
    for z in zeros:
        sum_z+=np.arctan2(-np.imag(z-p1),-np.real(z-p1))
        
    print(180+np.degrees(sum_z)-np.degrees(su

191.24248884660983

In [20]:
zeros

1.2094292028881888

In [21]:
roots

1.4056476493802699

In [14]:
zeros

-1.2094292028881888

In [26]:
360+np.degrees(roots)-np.degrees(zeros)-180

191.24248884660983

In [25]:
(180-np.degrees(roots)+np.degrees(zeros)+360)%360

168.75751115339017